spring:
  application:
    aiagent
  ai:
    openai:
      base-url: https://open.bigmodel.cn/api/paas/v4/  # 智谱AI API地址
      api-key: 28744fb1eef847c38e34cce83dcc2920.5tboGinC6vMR9e08 # 智谱AI APIKey
      embedding:
        embeddings-path: embeddings # 重新设置智谱AI的向量模型路径，覆盖openAi默认配置
        options:
          model: embedding-3 # 使用embedding-3文本向量模型
          dimensions: 2048 # 向量维度
      chat:
        completions-path: chat/completions # 重新设置智谱AI的聊天模型路径，覆盖openAi默认配置
        options:
          model: glm-4-flash # 使用glm-4-flash-250414语言模型

    vectorstore:
      elasticsearch:
        index-name: ticket-781-1-index     # 索引名称
        dimensions: 2048         # 必须与 Embedding 模型匹配
        initialize-schema: true   # 自动创建索引